<a href="https://colab.research.google.com/github/DimChatzMAI76/pytorch_tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])


In [3]:
#addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
#subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [6]:
#subfunction
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [7]:
#multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
#division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
#remainder modulus
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [12]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [13]:
#exponents/power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
#reassigment
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [17]:
tensor_a=tensor_a+tensor_b

In [18]:
tensor_a

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a=torch.tensor([1,2,3,4])

In [23]:
tensor_a

tensor([1, 2, 3, 4])

In [24]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a

tensor([ 6,  8, 10, 12])