<a href="https://colab.research.google.com/github/DimChatzMAI76/pytorch_tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [2]:
import torch
import numpy as np

In [5]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
np1=np.random.rand(3,4)
np1

array([[0.29213215, 0.58455672, 0.26152022, 0.71486257],
       [0.73356218, 0.54799712, 0.35889004, 0.13330156],
       [0.78506423, 0.44745129, 0.07454115, 0.8617939 ]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 1.0580,  1.5150, -0.4820, -0.7782],
        [ 0.1839, -0.9514, -0.5032, -0.4816],
        [-0.6114,  1.3578, -0.5374, -1.5472]])

In [9]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.2921, 0.5846, 0.2615, 0.7149],
        [0.7336, 0.5480, 0.3589, 0.1333],
        [0.7851, 0.4475, 0.0745, 0.8618]], dtype=torch.float64)